"use strict";
let estaChovendo = false;
estaChovendo = true;
let idade = 30;
let altura = 1.67;
const nacionalidade = 'brasileira';
const colegas = ['Lucas', 'Fernanda'];
const tecnologias = ['HTML', 'CSS', 'JS'];
const notas = [7, 9, 5, 8];
const lista = ['Felipe', true, 30];
let idadeDaAna = 25;
idadeDaAna = '25 anos';
let dadosDaApi;
dadosDaApi = 10;
dadosDaApi = true;
dadosDaApi = [1, 2, 3];
dadosDaApi = 'string';
let curso = 'front-end';
